{% set name = "mne-python" %}
{% set version = "1.7.1" %}
{% set sha256 = "a87bbc998b792532d2c87add8b0f7bbf28a4d8cf5db1bdfb6d6e260791754498" %}
{% set pymin = "3.9" %}
{% set build = 1 %}

# Adapted from https://github.com/conda-forge/vtk-feedstock/blob/main/recipe/meta.yaml
# PySide6 is lower priority than PyQt5 for backward compat (e.g., with matplotlib,
# mayavi, etc.) until the ecosystem updates
{% set build = build + 100 %}  # [build_variant == "pyside6"]
{% set build = build + 200 %}  # [build_variant == "pyqt"]
{% set build_string = '{}_py{}h{}_{}'.format(build_variant, CONDA_PY, PKG_HASH, build) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/mne/mne-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}

outputs:
  - name: mne-base
    build:
      noarch: python
      script: python -m pip install --no-deps . -vv
      entry_points:
        - mne = mne.commands.utils:main

    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python >={{ pymin }}
        - pip
        - hatchling
        - hatch-vcs
      run:
        - python >={{ pymin }}
        - matplotlib-base >=3.5.0
        - numpy >=1.21.2
        - scipy >=1.7.1
        - pooch >=1.5
        - tqdm
        - decorator
        - packaging
        - jinja2
        - importlib_resources >=5.10.2  # [py<=39]
        - lazy_loader >=0.3

    test:
      imports:
        - mne
      commands:
        - pip check  # [not win]
        - mne --version
      requires:
        - pip

  - name: mne
    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage('mne-base', max_pin="x.x.x.x") }}
        - __osx  # [osx]
        - pyobjc-framework-cocoa >=5.2.0  # [osx]  # for setting Dock icons etc
        - seaborn
        - jupyter
        - h5io
        - pymatreader
        - h5py
        - dipy
        - nibabel
        - nilearn
        - pandas >=0.23.4
        - xlrd
        - scikit-learn >=0.20.2
        - python-picard
        - numba
        - qtpy
        - vtk >=9.2
        - pyvista >=0.32
        - pyvistaqt >=0.4
        - statsmodels
        - numexpr
        - pyqt  # [build_variant == "pyqt"]
        - pyside6  # [build_variant == "pyside6"]
        - pillow
        - joblib
        - psutil
        - mffpy >=0.5.7
        - imageio >=2.6.1
        - imageio-ffmpeg >=0.4.1
        - traitlets
        - mne-qt-browser
        - ipywidgets
        - trame
        - trame-vtk
        - trame-vuetify
        - edfio
        - eeglabio
        - pybv
        - openmeeg >=2.5.6
        - defusedxml

    test:
      imports:
        - mne
      commands:
        - pip check  # [not win]
        - mne --version
      requires:
        - pip

  - name: mne-installer-menus
    requirements:
      build:
        - sed
      host:
        - python >={{ pymin }}
      run:
        - python >={{ pymin }}
        - mne-base

    build:
      skip: true  # [not linux]
      noarch: python
      script:
        - mkdir -p "{{ PREFIX }}/Menu"

        # Common
        - sed "s/__PKG_VERSION__/{{ PKG_VERSION }}/" "{{ RECIPE_DIR }}/menu/menu.json" > "{{ PREFIX }}/Menu/mne.json"

        # Spyder
        - cp "{{ RECIPE_DIR }}/menu/spyder.icns" "{{ PREFIX }}/Menu/mne_spyder.icns"
        - cp "{{ RECIPE_DIR }}/menu/spyder.ico" "{{ PREFIX }}/Menu/mne_spyder.ico"
        - cp "{{ RECIPE_DIR }}/menu/spyder.png" "{{ PREFIX }}/Menu/mne_spyder.png"

        # Console
        - cp "{{ RECIPE_DIR }}/menu/console.icns" "{{ PREFIX }}/Menu/mne_console.icns"
        - cp "{{ RECIPE_DIR }}/menu/console.ico" "{{ PREFIX }}/Menu/mne_console.ico"
        - cp "{{ RECIPE_DIR }}/menu/console.png" "{{ PREFIX }}/Menu/mne_console.png"
        # Use hash as separator, as PREFIX contains forward slashes!
        - sed "s#__PREFIX__#{{ PREFIX }}#" "{{ RECIPE_DIR }}/menu/open_prompt.applescript" > "{{ PREFIX }}/Menu/mne_open_prompt.applescript"  # for macOS
        - sed "s#__PREFIX__#{{ PREFIX }}#" "{{ RECIPE_DIR }}/menu/open_prompt.sh" > "{{ PREFIX }}/Menu/mne_open_prompt.sh"                    # for Linux
        - sed "s#__PREFIX__#{{ PREFIX }}#" "{{ RECIPE_DIR }}/menu/open_prompt.bat" > "{{ PREFIX }}/Menu/mne_open_prompt.bat"                  # for Windows

        # System info
        - cp "{{ RECIPE_DIR }}/menu/info.icns" "{{ PREFIX }}/Menu/mne_info.icns"
        - cp "{{ RECIPE_DIR }}/menu/info.ico" "{{ PREFIX }}/Menu/mne_info.ico"
        - cp "{{ RECIPE_DIR }}/menu/info.png" "{{ PREFIX }}/Menu/mne_info.png"
        - cp "{{ RECIPE_DIR }}/menu/mne_sys_info.py" "{{ PREFIX }}/Menu/mne_sys_info.py"

        # Website
        - cp "{{ RECIPE_DIR }}/menu/web.icns" "{{ PREFIX }}/Menu/mne_web.icns"
        - cp "{{ RECIPE_DIR }}/menu/web.ico" "{{ PREFIX }}/Menu/mne_web.ico"
        - cp "{{ RECIPE_DIR }}/menu/web.png" "{{ PREFIX }}/Menu/mne_web.png"

        # Forum
        - cp "{{ RECIPE_DIR }}/menu/forum.icns" "{{ PREFIX }}/Menu/mne_forum.icns"
        - cp "{{ RECIPE_DIR }}/menu/forum.ico" "{{ PREFIX }}/Menu/mne_forum.ico"
        - cp "{{ RECIPE_DIR }}/menu/forum.png" "{{ PREFIX }}/Menu/mne_forum.png"

        # Folder icon for macOS
        - cp "{{ RECIPE_DIR }}/menu/mne.png" "{{ PREFIX }}/Menu/mne.png"

    test:
      commands:
        - test -f ${CONDA_PREFIX}/Menu/mne.json
        - test -f ${CONDA_PREFIX}/Menu/mne_sys_info.py
        - test -f ${CONDA_PREFIX}/Menu/mne_open_prompt.applescript
        - test -f ${CONDA_PREFIX}/Menu/mne_open_prompt.sh
        - test -f ${CONDA_PREFIX}/Menu/mne_open_prompt.bat
        # Check we didn't forget any icons
        - test `ls ${CONDA_PREFIX}/Menu/mne_spyder.*  | wc -l` -eq 3
        - test `ls ${CONDA_PREFIX}/Menu/mne_console.* | wc -l` -eq 3
        - test `ls ${CONDA_PREFIX}/Menu/mne_info.*    | wc -l` -eq 3
        - test `ls ${CONDA_PREFIX}/Menu/mne_web.*     | wc -l` -eq 3
        - test `ls ${CONDA_PREFIX}/Menu/mne_forum.*   | wc -l` -eq 3
        - test -f ${CONDA_PREFIX}/Menu/mne.png

about:
  home: http://mne.tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MNE-Python is a software for MEG and EEG data analysis.
  description: |
    The main package for MNE-Python is named `mne` in conda-forge and should
    be suitable for most users. The conda recipe produces the following:

    - `mne`: should be installed for full functionality including 3D visualization.
    - `mne-base`: only pulls dependencies for basic functionality and 2D visualization.
    - `mne-installer-menus`: should not be installed manually, as it is only meant to be used by the standalone installers.
  doc_url: http://mne.tools
  dev_url: https://github.com/mne-tools/mne-python

extra:
  recipe-maintainers:
    - larsoner
    - christianbrodbeck
    - hoechenberger
