{% set name = "mne" %}
{% set version = "0.21.0" %}
{% set sha256 = "3427af8b2cf52f7b85a4ed5703a998a4e86ca3e37b78cf82881551264d855076" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mne = mne.commands.utils:main
  skip: true  # [py <35]

requirements:
  build:
    - python
    - pip
  run:
    - python
    - dipy
    - matplotlib-base
    - nibabel
    - nilearn
    - pandas >=0.18
    - xlrd
    - numpy
    - scikit-learn
    - scipy
    - mayavi
    - pysurfer
    - python-picard
    - numba
    - pyvista >=0.24
    - tqdm
    - h5py
    - statsmodels
    - numexpr
    - pyqt >=5.9         # [not osx]
    - pyqt >=5.10,<5.14  # [osx]
    - pillow
    - joblib
    - psutil

test:
  imports:
    - mne
  commands:
    - mne --version

about:
  home: http://mne.tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MNE-Python is a software for MEG and EEG data analysis.
  doc_url: http://mne.tools
  dev_url: https://github.com/mne-tools/mne-python

extra:
  recipe-maintainers:
    - larsoner
    - christianbrodbeck
    - hoechenberger
