{% set name = "mne" %}
{% set version = "0.20.7" %}
{% set sha256 = "1c63ec338a5677664679bb94fd1eea55dc83486457ad94409927aab3a047604b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [py<36]

outputs:
  - name: mne-base

    script: build_base.bat  # [win]
    script: build_base.sh   # [not win]

    build:
      entry_points:
        - mne = mne.commands.utils:main

    requirements:
      host:
        - python
        - pip
      run:
        - python
        - numpy
        - scipy
        - matplotlib-base

    test:
      imports:
        - mne
      commands:
        - mne --version
        - mne sys_info

  - name: mne

    requirements:
      run:
        - dipy
        - nibabel
        - nilearn
        - pandas >=0.18
        - xlrd
        - scikit-learn
        - mayavi
        - pysurfer
        - python-picard
        - numba
        - pyvista >=0.24
        - tqdm
        - h5py
        - statsmodels
        - numexpr
        - pyqt >=5.9         # [not osx]
        - pyqt >=5.10,<5.14  # [osx]
        - pillow
        - joblib
        - psutil
        - {{ pin_subpackage('mne-base', exact=True) }}

    test:
      imports:
        - mne
      commands:
        - mne --version
        - mne sys_info

about:
  home: http://mne.tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MNE-Python is a software for MEG and EEG data analysis.
  dev_url: https://github.com/mne-tools/mne-python

extra:
  recipe-maintainers:
    - larsoner
    - christianbrodbeck
    - hoechenberger
