{% set name = "mne" %}
{% set version = "0.22.0" %}
{% set sha256 = "63cf8a7985a350ff2b4dc64d1071044eceaca30f1a8ff51a2dc0552d122326a5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mne = mne.commands.utils:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dipy
    - matplotlib-base >=3.0
    - nibabel
    - nilearn
    - pandas >=0.23.4
    - xlrd
    - numpy >=1.15.4
    - scikit-learn >=0.20.2
    - scipy >=1.1.0
    - mayavi
    - pysurfer
    - python-picard
    # - numba  Re-enable once https://github.com/conda-forge/numba-feedstock/pull/64 has been resolved
    - vtk >=9.0.1
    - pyvista >=0.24
    - pyvistaqt >=0.2.0
    - tqdm
    - h5py
    - statsmodels
    - numexpr
    - pyqt
    - pillow
    - joblib
    - psutil
    - mffpy >=0.5.7
    - imageio
    - imageio-ffmpeg >=0.4.1
    - traits
    - traitsui
    - pyface

test:
  imports:
    - mne
  commands:
    - mne --version

about:
  home: http://mne.tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MNE-Python is a software for MEG and EEG data analysis.
  doc_url: http://mne.tools
  dev_url: https://github.com/mne-tools/mne-python

extra:
  recipe-maintainers:
    - larsoner
    - christianbrodbeck
    - hoechenberger
