{% set name = "mne-python" %}
{% set version = "1.0dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/mne-tools/mne-python.git
  # git_depth: 1
  git_rev: main

build:
  number: 20220214

outputs:
  - name: mne-base
    build:
      noarch: python
      script: python -m pip install --no-deps . -vv
      entry_points:
        - mne = mne.commands.utils:main

    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - setuptools
        - matplotlib-base >=3.1.0
        - numpy >=1.15.4
        - scipy >=1.1.0
        - pooch >=1.5
        - tqdm
        - decorator
        - packaging
        - jinja2

    test:
      requires:
        - pip
      imports:
        - mne
      commands:
        - pip check
        - mne --version

  - name: mne
    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage('mne-base', max_pin="x.x.x.x") }}
        - matplotlib >=3.1.0
        - jupyter
        - h5io
        - pymatreader
        - h5py
        - dipy
        - nibabel
        - nilearn
        - pandas >=0.23.4
        - xlrd
        - scikit-learn >=0.20.2
        - python-picard
        - numba
        - vtk >=9.0.1
        - pyvista >=0.32
        - pyvistaqt >=0.4
        - statsmodels
        - numexpr
        - pyqt
        - pillow
        - joblib
        - psutil
        - mffpy >=0.5.7
        - imageio >=2.6.1
        - imageio-ffmpeg >=0.4.1
        - traits
        - traitsui
        - traitlets
        - mne-qt-browser
        - ipywidgets
        - ipyvtklink

    test:
      requires:
        - pip
      imports:
        - mne
      commands:
        - pip check
        - mne --version

about:
  home: http://mne.tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MNE-Python is a software for MEG and EEG data analysis.
  doc_url: http://mne.tools
  dev_url: https://github.com/mne-tools/mne-python

extra:
  recipe-maintainers:
    - larsoner
    - christianbrodbeck
    - hoechenberger
