{% set name = "mne-python" %}
{% set version = "1.0dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/mne-tools/mne-python.git
  git_depth: 1
  git_rev: main

build:
  number: 20220218

outputs:
  - name: mne-base
    about:
      description: |
        This package contains the basic functionality for data analysis and 2D
        visualization. For full functionality, including 3D visualization,
        use the `mne` package instead.

    build:
      noarch: python
      script: python -m pip install --no-deps . -vv
      entry_points:
        - mne = mne.commands.utils:main

    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - setuptools
        - matplotlib-base >=3.1.0
        - numpy >=1.15.4
        - scipy >=1.1.0
        - pooch >=1.5
        - tqdm
        - decorator
        - packaging
        - jinja2

    test:
      requires:
        - pip
      imports:
        - mne
      commands:
        - pip check
        - mne --version

  - name: mne
    about:
      description: |
        This package contains the full functionality including 3D
        visualization. This means that this package has numerous dependencies.
        If you only need basic functionality and 2D visualization, use the
        `mne-base` package instead.

    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage('mne-base', max_pin="x.x.x.x") }}
        - matplotlib >=3.1.0
        - jupyter
        - h5io
        - pymatreader
        - h5py
        - dipy
        - nibabel
        - nilearn
        - pandas >=0.23.4
        - xlrd
        - scikit-learn >=0.20.2
        - python-picard
        - numba
        - vtk >=9.0.1
        - pyvista >=0.32
        - pyvistaqt >=0.4
        - statsmodels
        - numexpr
        - pyqt
        - pillow
        - joblib
        - psutil
        - mffpy >=0.5.7
        - imageio >=2.6.1
        - imageio-ffmpeg >=0.4.1
        - traitlets
        - mne-qt-browser
        - ipywidgets
        - ipyvtklink

    test:
      requires:
        - pip
      imports:
        - mne
      commands:
        - pip check
        - mne --version

  - name: mne-installer-menus
    about:
      summary: Menus for MNE-Python. This package is only used by the MNE-Python installers

    requirements:
      build:
        - sed
      host:
        - python >=3.7
      
      run:
        - python >=3.7
        - mne-base
        - spyder

    build:
      noarch: python
      script:
        - mkdir -p "{{ PREFIX }}/Menu"

        # Common
        - sed "s/__PKG_VERSION__/{{ PKG_VERSION }}/" "{{ RECIPE_DIR }}/menu/menu.json" > "{{ PREFIX }}/Menu/mne.json"

        # Spyder
        - cp "{{ RECIPE_DIR }}/menu/spyder.icns" "{{ PREFIX }}/Menu/mne_spyder.icns"
        - cp "{{ RECIPE_DIR }}/menu/spyder.ico" "{{ PREFIX }}/Menu/mne_spyder.ico"

        # Console
        - cp "{{ RECIPE_DIR }}/menu/console.icns" "{{ PREFIX }}/Menu/mne_console.icns"
        - cp "{{ RECIPE_DIR }}/menu/console.ico" "{{ PREFIX }}/Menu/mne_console.ico"
        # Use hash as separator, as PREFIX contains forward slashes!
        - sed "s#__PREFIX__#{{ PREFIX }}#" "{{ RECIPE_DIR }}/menu/open_prompt.applescript" > "{{ PREFIX }}/Menu/mne_open_prompt.applescript"

        # System info
        - cp "{{ RECIPE_DIR }}/menu/info.icns" "{{ PREFIX }}/Menu/mne_info.icns"
        - cp "{{ RECIPE_DIR }}/menu/info.ico" "{{ PREFIX }}/Menu/mne_info.ico"
        - cp "{{ RECIPE_DIR }}/menu/mne_sys_info.py" "{{ PREFIX }}/Menu/mne_sys_info.py"

        # Website
        - cp "{{ RECIPE_DIR }}/menu/web.icns" "{{ PREFIX }}/Menu/mne_web.icns"
        - cp "{{ RECIPE_DIR }}/menu/web.ico" "{{ PREFIX }}/Menu/mne_web.ico"

        # Forum
        - cp "{{ RECIPE_DIR }}/menu/forum.icns" "{{ PREFIX }}/Menu/mne_forum.icns"
        - cp "{{ RECIPE_DIR }}/menu/forum.ico" "{{ PREFIX }}/Menu/mne_forum.ico"

    test:
      commands:
        - test -f ${CONDA_PREFIX}/Menu/mne.json
        - test -f ${CONDA_PREFIX}/Menu/mne_sys_info.py

about:
  home: http://mne.tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MNE-Python is a software for MEG and EEG data analysis.
  doc_url: http://mne.tools
  dev_url: https://github.com/mne-tools/mne-python

extra:
  recipe-maintainers:
    - larsoner
    - christianbrodbeck
    - hoechenberger
