{% set name = "mne" %}
{% set version = "0.19.2" %}
{% set sha256 = "8348ae99a75a9b448c62a60c2e28e27316b6d4d0ec20c98d9f9dad1c4cd0ff75" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - dipy
    - matplotlib
    - nibabel
    - numpy
    - scikit-learn
    - scipy
    - mayavi
    - pysurfer
    - python-picard

test:
  imports:
    - mne
  commands:
    - mne

about:
  home: http://martinos.org/mne
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'MNE python project for MEG and EEG data analysis.'
  description: |
    MNE python project for MEG and EEG data analysis.
  doc_url: http://martinos.org/mne
  dev_url: https://github.com/mne-tools/mne-python

extra:
  recipe-maintainers:
    - larsoner
    - christianbrodbeck
