{% set name = "mne-python" %}
{% set version = "1.10.0" %}
{% set sha256 = "70a615dcfc2fdde891d2e5d2d714c352ffc64c52685ea6c1b031a6c189f6d8a9" %}
{% set build = 0 %}
{% set python_min = "3.10" %}

# Adapted from https://github.com/conda-forge/vtk-feedstock/blob/main/recipe/meta.yaml
# PySide6 is lower priority than PyQt5 for backward compat (e.g., with matplotlib,
# mayavi, etc.) until the ecosystem updates
{% set build = build + 100 %}  # [build_variant == "pyside6"]
{% set build = build + 200 %}  # [build_variant == "pyqt"]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/m/mne/mne-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}

outputs:
  - name: mne-base
    build:
      noarch: python
      script: python -m pip install --no-deps . -vv
      entry_points:
        - mne = mne.commands.utils:main

    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python {{ python_min }}
        - pip
        - hatchling
        - hatch-vcs
      run:
        - python >={{ python_min }}
        - matplotlib-base >=3.7
        - numpy >=1.25
        - scipy >=1.11
        - pooch >=1.5
        - tqdm
        - decorator
        - packaging
        - jinja2
        - lazy_loader >=0.3

    test:
      imports:
        - mne
      commands:
        - pip check  # [not win]
        - mne --version
      requires:
        - python {{ python_min }}
        - pip

  - name: mne
    build:
      string: "osx_{{ build_variant }}_h{{ PKG_HASH }}_{{ build }}"  # [osx]
      string: "linux_{{ build_variant }}_h{{ PKG_HASH }}_{{ build }}"  # [linux]
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('mne-base', max_pin="x.x.x.x") }}
        - __osx  # [osx]
        - pyobjc-framework-cocoa >=5.2.0  # [osx]  # for setting Dock icons etc
        - seaborn
        - jupyter
        - h5io
        - pymatreader
        - h5py
        - dipy
        - nibabel
        - nilearn
        - pandas >=0.23.4
        - xlrd
        - scikit-learn >=1.3
        - python-picard
        - numba
        - qtpy
        - vtk >=9.2
        - pyvista >=0.32
        - pyvistaqt >=0.4
        - statsmodels
        - numexpr
        - pyqt  # [build_variant == "pyqt"]
        - pyside6  # [build_variant == "pyside6"]
        - pillow
        - joblib
        - psutil
        - mffpy >=0.5.7
        - imageio >=2.6.1
        - imageio-ffmpeg >=0.4.1
        - traitlets
        - mne-qt-browser
        - ipywidgets
        - trame
        - trame-vtk
        - trame-vuetify
        - edfio >=0.2.1
        - antio >=0.5
        - eeglabio
        - pybv
        - openmeeg >=2.5.6
        - defusedxml

    test:
      imports:
        - mne
      commands:
        - pip check  # [not win]
        - mne --version
      requires:
        - python {{ python_min }}
        - pip

about:
  home: http://mne.tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MNE-Python is a software for MEG and EEG data analysis.
  description: |
    The main package for MNE-Python is named `mne` in conda-forge and should
    be suitable for most users. The conda recipe produces the following:

    - `mne`: should be installed for full functionality including 3D visualization.
    - `mne-base`: only pulls dependencies for basic functionality and 2D visualization.
  doc_url: http://mne.tools
  dev_url: https://github.com/mne-tools/mne-python

extra:
  recipe-maintainers:
    - larsoner
    - christianbrodbeck
    - hoechenberger
